% We're adding the 'comments' field to the fly table
% We're adding the 'pmtVoltage' field to stimulusPresentation
% Adding expression system table
% Adding expressionSystemFlyJoin to join the two
% Added 6/7/2016
conn = connectToDatabase('/Users/emilio/Documents/flyStuff/experimentLog.db');

%% New comments column in fly table
FlyBackupTableSQLQuery = ['CREATE TABLE flyBackup ('...
    'flyId INTEGER PRIMARY KEY,'...
    'relativePath TEXT,'...
    'genotype TEXT,'...
    'cellType TEXT,'...
    'fluorescentProtein INT,'...
    'surgeon TEXT,'...
    'eye TEXT,'...
    'condition INT,'...
    'behaviorId TEXT UNIQUE,'...
    'comments TEXT)']; % new column

exec(conn, FlyBackupTableSQLQuery)

FlyBackupInsertCall = ...
    ['INSERT INTO flyBackup '...
        '(flyId, '...
        'relativePath, '...
        'genotype, '...
        'cellType, '...
        'fluorescentProtein, '...
        'surgeon, '...
        'eye, '...
        'condition, '...
        'behaviorId) '...
    'SELECT '...
        'flyId, '...'
        'relativePath, '...
        'genotype, '...
        'cellType, '...
        'fluorescentProtein, '...
        'surgeon, '...
        'eye, '...
        'condition, '...
        'behaviorId '...
    'FROM fly'];

exec(conn, FlyBackupInsertCall)

FlyDropCall = 'DROP TABLE fly';

exec(conn, FlyDropCall)

FlyBackupRenameCall = 'ALTER TABLE flyBackup RENAME TO fly';

exec(conn, FlyBackupRenameCall)

%% New pmtVoltage column in stimulusPresentation
StimulusPresentationTableSQLQuery = ['CREATE TABLE stimulusPresentationBackup ('...
    'stimulusPresentationId INTEGER PRIMARY KEY,'...
    'fly INT,'...
    'relativeDataPath TEXT,'...
    'stimulusFunction TEXT,'...
    'comments TEXT,'...
    'laserPower REAL,'...
    'pmtVoltage INT,'... % new column
    'dataQuality INT,'...
    'perfusion INT,'...
    'date TEXT,'...
    'tags TEXT,'...
    'cylinderRotation REAL,'...
    'flyHeight REAL, FOREIGN KEY(fly) REFERENCES fly(flyId))'];

exec(conn, StimulusPresentationTableSQLQuery)

StimulusPresentationInsertCall = ...
    ['INSERT INTO stimulusPresentationBackup'...
        '(stimulusPresentationId, '...
        'fly, '...
        'relativeDataPath, '...
        'stimulusFunction, '...
        'comments, '...
        'laserPower, '...
        'dataQuality, '...
        'perfusion, '...
        'date, '...
        'tags, '...
        'cylinderRotation, '...
        'flyHeight) '...
    'SELECT '...
        'stimulusPresentationId, '...
        'fly, '...
        'relativeDataPath, '...
        'stimulusFunction, '...
        'comments, '...
        'laserPower, '...
        'dataQuality, '...
        'perfusion, '...
        'date, '...
        'tags, '...
        'cylinderRotation, '...
        'flyHeight '...
    'FROM stimulusPresentation'];

exec(conn, StimulusPresentationInsertCall)

StimulusPresentationDropCall = 'DROP TABLE stimulusPresentation';

exec(conn, StimulusPresentationDropCall)

StimulusPresentationBackupRenameCall = 'ALTER TABLE stimulusPresentationBackup RENAME TO stimulusPresentation';

exec(conn, StimulusPresentationBackupRenameCall)

%% New expressionSystem table
ExpressionSystemTableSQLQuery = ['CREATE TABLE expressionSystem ('...
    'expressionSystemId INTEGER PRIMARY KEY,'...
    'name TEXT UNIQUE)']; % new column

exec(conn, ExpressionSystemTableSQLQuery)

%% New expressionSystemFlyJoin many-to-many join table
ExpressionSystemFlyJoinTableSQLQuery = ['CREATE TABLE expressionSystemFlyJoin ('...
    'esfId INTEGER PRIMARY KEY,'...
    'fly INT,'...
    'expressionSystem INT,'...
    'FOREIGN KEY(fly) REFERENCES fly(flyId),'...
    'FOREIGN KEY(expressionSystem) REFERENCES expressionSystem(expressionSystemId))']; % new column

exec(conn, ExpressionSystemFlyJoinTableSQLQuery)