% We're adding the 'comments', 'perfusion', and 'rotation' fields to the stimulusPresentation table
% Added 6/26/2015
conn = connectToDatabase;

StimulusPresentationTableSQLQuery = ['CREATE TABLE stimulusPresentationBackup ('...
    'stimulusPresentationId INTEGER PRIMARY KEY,'...
    'fly INT,'...
    'relativeDataPath TEXT,'...
    'stimulusFunction TEXT,'...
    'comments TEXT,'...
    'perfusion INT,'...
    'dataQuality INT,'...
    'date TEXT,'...
    'tags TEXT,'...
    'cylinderRotation REAL,'...
    'flyHeight REAL, FOREIGN KEY(fly) REFERENCES fly(flyId))'];

exec(conn, StimulusPresentationTableSQLQuery)

StimulusPresentationInsertCall = ['INSERT INTO stimulusPresentationBackup (stimulusPresentationId, fly, relativeDataPath, stimulusFunction, dataQuality, date, tags) '...
    'SELECT stimulusPresentationId, fly, relativeDataPath, stimulusFunction, dataQuality, date, tags '...
    'FROM stimulusPresentation'];

exec(conn, StimulusPresentationInsertCall)

StimulusPresentationDropCall = 'DROP TABLE stimulusPresentation';

exec(conn, StimulusPresentationDropCall)

StimulusPresentationBackupRenameCall = 'ALTER TABLE stimulusPresentationBackup RENAME TO stimulusPresentation';

exec(conn, StimulusPresentationBackupRenameCall)