% We're adding the 'behaviorId' field to the fly table and 'laserPower' to
% the stimulusPresentation table
% Added 9/1/2015
conn = connectToDatabase;

FlyBackupTableSQLQuery = ['CREATE TABLE flyBackup ('...
    'flyId INTEGER PRIMARY KEY,'...
    'relativePath TEXT,'...
    'genotype TEXT,'...
    'cellType TEXT,'...
    'fluorescentProtein TEXT,'...
    'surgeon TEXT,'...
    'eye TEXT,'...
    'condition INT,'...
    'behaviorId TEXT UNIQUE)'];

exec(conn, FlyBackupTableSQLQuery)

FlyBackupInsertCall = ['INSERT INTO flyBackup (flyId, relativePath, genotype, cellType, fluorescentProtein, surgeon, eye, condition) '...
    'SELECT flyId, relativePath, genotype, cellType, fluorescentProtein, surgeon, eye, condition '...
    'FROM fly'];

exec(conn, FlyBackupInsertCall)

FlyDropCall = 'DROP TABLE fly';

exec(conn, FlyDropCall)

FlyBackupRenameCall = 'ALTER TABLE flyBackup RENAME TO fly';

exec(conn, FlyBackupRenameCall)

StimulusPresentationTableSQLQuery = ['CREATE TABLE stimulusPresentationBackup ('...
    'stimulusPresentationId INTEGER PRIMARY KEY,'...
    'fly INT,'...
    'relativeDataPath TEXT,'...
    'stimulusFunction TEXT,'...
    'comments TEXT,'...
    'laserPower REAL,'...
    'dataQuality INT,'...
    'perfusion INT,'...
    'date TEXT,'...
    'tags TEXT,'...
    'cylinderRotation REAL,'...
    'flyHeight REAL, FOREIGN KEY(fly) REFERENCES fly(flyId))'];

exec(conn, StimulusPresentationTableSQLQuery)

StimulusPresentationInsertCall = ['INSERT INTO stimulusPresentationBackup (stimulusPresentationId, fly, relativeDataPath, stimulusFunction, comments, dataQuality, perfusion, date, tags, cylinderRotation, flyHeight) '...
    'SELECT stimulusPresentationId, fly, relativeDataPath, stimulusFunction, comments, dataQuality, perfusion, date, tags, cylinderRotation, flyHeight '...
    'FROM stimulusPresentation'];

exec(conn, StimulusPresentationInsertCall)

StimulusPresentationDropCall = 'DROP TABLE stimulusPresentation';

exec(conn, StimulusPresentationDropCall)

StimulusPresentationBackupRenameCall = 'ALTER TABLE stimulusPresentationBackup RENAME TO stimulusPresentation';

exec(conn, StimulusPresentationBackupRenameCall)