% We're adding the 'surgeon' field to the fly table
% Added 2/25/2015
conn = connectToDatabase;

FlyBackupTableSQLQuery = ['CREATE TABLE flyBackup ('...
    'flyId INTEGER PRIMARY KEY,'...
    'relativePath TEXT,'...
    'genotype TEXT,'...
    'cellType TEXT,'...
    'fluorescentProtein TEXT,'...
    'surgeon TEXT,'...
    'eye TEXT,'...
    'condition INT)'];

exec(conn, FlyBackupTableSQLQuery)

FlyBackupInsertCall = ['INSERT INTO flyBackup (flyId, relativePath, genotype, cellType, fluorescentProtein, eye, condition) '...
    'SELECT flyId, relativePath, genotype, cellType, fluorescentProtein, eye, condition '...
    'FROM fly'];

exec(conn, FlyBackupInsertCall)

FlyDropCall = 'DROP TABLE fly';

exec(conn, FlyDropCall)

FlyBackupRenameCall = 'ALTER TABLE flyBackup RENAME TO fly';

exec(conn, FlyBackupRenameCall)