% Initial database creation!
% Added 12/10/2014 <- this is an estimate
conn = connectToDatabase;

FlyTableSQLQuery = ['CREATE TABLE fly ('...
    'flyId INTEGER PRIMARY KEY,'...
    'relativePath TEXT,'...
    'genotype TEXT,'...
    'cellType TEXT,'...
    'fluorescentProtein TEXT,'...
    'eye TEXT,'...
    'condition INT)'];
StimulusRunSQLQuery = ['CREATE TABLE stimulusPresentation ('...
    'stimulusPresentationId INTEGER PRIMARY KEY,'...
    'fly INT,'...
    'relativeDataPath TEXT,'...
    'stimulusFunction TEXT,'...
    'dataQuality INT,'...
    'date TEXT,'...
    'tags TEXT, FOREIGN KEY(fly) REFERENCES fly(flyId))'];
AnalysisRunTableSQLQuery = ['CREATE TABLE analysisRun ('...
    'runDate TEXT UNIQUE,'...
    'stimulus INT,'...
    'comments TEXT,'...
    'functionCall TEXT,'...
    'analysisMethod TEXT,'...
    'runInfoVariable TEXT,'...
    'analysisQuality INT,'...
    'gitCommit TEXT,'...
    'gitPatch TEXT, FOREIGN KEY (stimulus) REFERENCES stimulusPresentation(stimulusPresentationId))'];

exec(conn, FlyTableSQLQuery);
exec(conn, StimulusRunSQLQuery);
exec(conn, AnalysisRunTableSQLQuery);