% We're correcting the 'fluorescentProtein' field to TEXT from INT in the fly table
% We're adding the 'pmt1Voltage' and 'pmt2Voltage' fields and removing the 'pmtVoltage' field to stimulusPresentation
% We're adding the 'probeStimulusFunction' field to stimulusPresentation
% Added 9/20/2016
conn = connectToDatabase;

%% Correct the fact that fluorescentProtein was listed as an INT, not a TEXT
FlyBackupTableSQLQuery = ['CREATE TABLE flyBackup ('...
    'flyId INTEGER PRIMARY KEY,'...
    'relativePath TEXT,'...
    'genotype TEXT,'...
    'cellType TEXT,'...
    'fluorescentProtein TEXT,'... % changed column
    'surgeon TEXT,'...
    'eye TEXT,'...
    'condition INT,'...
    'behaviorId TEXT UNIQUE,'...
    'overallComments TEXT)'];

exec(conn, FlyBackupTableSQLQuery)

FlyBackupInsertCall = ...
    ['INSERT INTO flyBackup '...
        '(flyId, '...
        'relativePath, '...
        'genotype, '...
        'cellType, '...
        'fluorescentProtein, '...
        'surgeon, '...
        'eye, '...
        'condition, '...
        'behaviorId, '...
        'overallComments) '...
    'SELECT '...
        'flyId, '...
        'relativePath, '...
        'genotype, '...
        'cellType, '...
        'fluorescentProtein, '...
        'surgeon, '...
        'eye, '...
        'condition, '...
        'behaviorId, '...
        'overallComments '...
    'FROM fly'];

exec(conn, FlyBackupInsertCall)

FlyDropCall = 'DROP TABLE fly';

exec(conn, FlyDropCall)

FlyBackupRenameCall = 'ALTER TABLE flyBackup RENAME TO fly';

exec(conn, FlyBackupRenameCall)

%% New pmt1Voltage, pmt2voltage, and probeStimulusFunction columns in stimulusPresentation
StimulusPresentationTableSQLQuery = ['CREATE TABLE stimulusPresentationBackup ('...
    'stimulusPresentationId INTEGER PRIMARY KEY,'...
    'fly INT,'...
    'relativeDataPath TEXT,'...
    'stimulusFunction TEXT,'...
    'comments TEXT,'...
    'probeStimulusFunction TEXT,'... % new column
    'laserPower REAL,'...
    'pmtAVoltage INT,'... % new column
    'pmtBVoltage INT,'... % new column
    'dataQuality INT,'...
    'perfusion INT,'...
    'date TEXT,'...
    'tags TEXT,'...
    'cylinderRotation REAL,'...
    'flyHeight REAL, FOREIGN KEY(fly) REFERENCES fly(flyId))'];

exec(conn, StimulusPresentationTableSQLQuery)

StimulusPresentationInsertCall = ...
    ['INSERT INTO stimulusPresentationBackup'...
        '(stimulusPresentationId, '...
        'fly, '...
        'relativeDataPath, '...
        'stimulusFunction, '...
        'comments, '...
        'laserPower, '...
        'pmtAVoltage, '... % This data will get pmtVoltage, with a few manual corrections
        'dataQuality, '...
        'perfusion, '...
        'date, '...
        'tags, '...
        'cylinderRotation, '...
        'flyHeight) '...
    'SELECT '...
        'stimulusPresentationId, '...
        'fly, '...
        'relativeDataPath, '...
        'stimulusFunction, '...
        'comments, '...
        'laserPower, '...
        'pmtVoltage, '...
        'dataQuality, '...
        'perfusion, '...
        'date, '...
        'tags, '...
        'cylinderRotation, '...
        'flyHeight '...
    'FROM stimulusPresentation'];

exec(conn, StimulusPresentationInsertCall)

StimulusPresentationDropCall = 'DROP TABLE stimulusPresentation';

exec(conn, StimulusPresentationDropCall)

StimulusPresentationBackupRenameCall = 'ALTER TABLE stimulusPresentationBackup RENAME TO stimulusPresentation';

exec(conn, StimulusPresentationBackupRenameCall)

close(conn)
