function result = GetPhotoDiodeFlashState(framesSinceEpochChange,epochNum)
    epochBinary = dec2bin(epochNum);
    frame_current = framesSinceEpochChange;
    result = (frame_current <= length(epochBinary)+1) && ( ...
        (frame_current == 0) || ...
        (frame_current == length(epochBinary) + 1) || ...
        (logical(str2double(epochBinary(frame_current)))) ...
    );