function LegendWithTitle(entries,title)
    lh = legend(entries);
    set(lh,'box','off','FontSize',16);
    
    finalTitle = cell(length(entries)+1,1);
    finalTitle = cellfun(@(x)({''}),finalTitle);
    finalTitle{1} = title;
    
    text(...
    'Parent', lh.DecorationContainer, ...
    'String', finalTitle, ...
    'HorizontalAlignment', 'center', ...
    'VerticalAlignment', 'baseline', ...
    'Position', [0.5, 1.05, 0], ...
    'FontSize', 16, ...
    'HitTest', 'off', ...
    'Units', 'normalized');

%     'LineWidth',2.0, ...
%     'EdgeColor', [0, 0, 0], ...
end