function SaveFigs(folderName)
% This function allows you to quickly save all currently open figures with
% a custom filename for each in multiple formats.  To use the function
% simply call savefigs with no arguments, then follow the prompts
%
% Upon execution this function will one-by-one bring each currently open
% figure to the foreground.  Then it will supply a text prompt in the main
% console window asking you for a filename.  It will save that figure to
% that filename in the .fig, .emf, .png, and .eps formats.
%
% The formats that it saves in can be changed by commenting out or adding
% lines below.
%
% Copyright 2010 Matthew Guidry
% matt.guidry ATT gmail DOTT com  (Email reformatted for anti-spam)

%% MODIFIED BY MATT CREAMER to work specifically with the fly psychophysics computer
% in this version all you do is designate a folder nam and it saves all current to the
% logbook/figures folder with a bunch of different data types as well
% as extracting the xy data


sysConfig = GetSystemConfiguration();
logFolder = sysConfig.logPath;

hFigs = get(0, 'children'); %Get list of figures
if verLessThan('matlab', '8.4')
    hFigs = sort(hFigs);
else
    [~, srtInds] = sort([hFigs.Number]);
    hFigs = hFigs(srtInds);
end
%     hfigs = findall(0,'type','figure');

[~, filename, ~] = fileparts(folderName);
powerPointName = fullfile(logFolder,'figures',folderName,filename);

if ismac
    isOpen  = exportToPPTX();
    if ~isempty(isOpen),
        % If PowerPoint already started, then close first and then open a new one
        exportToPPTX('close');
    end
    
    exportToPPTX('new','Dimensions',[10 5.63], ... This is 16x9 formatting
        'Title','Example Presentation', ...
        'Author','MatLab', ...
        'Subject','Automatically generated PPTX file', ...
        'Comments','This file has been automatically generated by exportToPPTX');
end

for hh = 1:length(hFigs)
    if verLessThan('matlab', '8.4')
        filename = ['fig' num2str(hh)];
    else
        if ~isempty(hFigs(hh).Name)
            filename = hFigs(hh).Name;
            filename(filename=='.') = '-';
            filename(filename == ' ') = '_';
            filename = [filename '_' num2str(hh)];
            filename(filename == '/') = '_';
        else
            filename = ['fig' num2str(hh)];
        end
    end
    
    path = fullfile(logFolder,'figures',folderName,filename,filename);
    mkdir(fullfile(logFolder,'figures',folderName,filename));
    %
    %         set(hfigs(hh),'PaperPositionMode','auto');
    %         print(hfigs(hh),path,'-dpng','-r0');
    
    
    
    savefig(hFigs(hh),path);
    
    axisHandles = findall(hFigs(hh),'type','axes');
    set(axisHandles,'Color','none');
    export_fig(hFigs(hh),path,'-png', '-eps','-transparent','-painters')
    %         print(hfigs(hh),'-dpdf',path);
    if ispc
        saveppt2(powerPointName,'figure',hFigs(hh), 'title', filename);
    elseif ismac
        slideNum = exportToPPTX('addslide');
        exportToPPTX('addpicture',hFigs(hh));
        exportToPPTX('addtext',filename);
    end
    
    %         set(gcf, 'renderer', 'painters');
    %         print(hfigs(hh),'-depsc2',[path '.eps']);
    %         print([path '.eps']);
end

if ismac
    exportToPPTX('saveandclose',powerPointName);
end

end